# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(41d03a59-4589-4a89-b70c-779281943656)'
    subscriptionId: '41d03a59-4589-4a89-b70c-779281943656'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'devopsrg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/RonyM007/testrepo/main/webapp/azuredeploy.json'
    overrideParameters: '-projectName hello world'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
